package com.example.exploremateapp;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Places implements Serializable {
    String country;
    String place;
    String desc;
    int img;
    String history;

    public String getHistory() {
        return history;
    }

    public void setHistory(String history) {
        this.history = history;
    }

    public Places(String country, String place, String desc, int img, String history) {
        this.country = country;
        this.place = place;
        this.desc = desc;
        this.img = img;
        this.history =history;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public int getImg() {
        return img;
    }

    public void setImg(int img) {
        this.img = img;
    }
    public static List<Places> getAllPlaces(){
        Places I1 = new Places("Italy","Trevi Fountain","This site is best viewed at night when lights illuminate the fountain. However, some travelers lament the Trevi's many tourists and aggressive local street vendors (you'll likely have a hard time getting a crowd-free photo here). The Trevi Fountain sits off the Barberini metro stop and is about a 10-minute walk east of the Pantheon. It is free to visit 24/7. If you don't plan a visit on your own, you'll likely pass by the fountain if you sign up for one of the best Rome tours.",R.drawable.italy_trevi,"It was designed by Nicola Salvi and completed by Giuseppe Pannini in 1762. According to legend, those who toss coins into its waters will return to Rome. The fountain is located in Rome's Trevi district, abutting the Palazzo Poli.");
        Places I2 = new Places("Italy","Piazza della Signoria","Take your time wandering around, and if you get tired, grab a seat along the Loggia dei Lanzi, or make your way to a cafe near the Fountain of Neptune. Recent visitors said this is a must-see spot and a great area to people-watch, view magnificent sculptures and rest travel-weary feet (though past travelers recommended avoiding the restaurants in this area, calling them \"outrageously overpriced\"). To avoid the height of the crowds, visit in the early morning or the evening. Access to the area is free 24/7.",R.drawable.italy_piazza,"It is the main point of the origin and history of the Florentine Republic and still maintains its reputation as the political focus of the city. It is the meeting place of Florentines as well as the numerous tourists, located near Palazzo Vecchio and Piazza del Duomo and gateway to Uffizi Gallery.");
        Places I3 = new Places("Italy","Cathedral of Santa Maria del Fiore","The Cattedrale di Santa Maria del Fiore (known simply as the Duomo) is not only Florence's religious center, but it's also the city's most recognizable attraction. Occupying the Piazza del Duomo in the heart of the city, this massive Gothic cathedral was erected during the 14th century on the former site of the Roman church, Santa Reparata. You'll know you're in the right place when you find yourself straining your neck to see the church's massive, iconic dome and the intricate marble statues on its facade staring down at you. The red-tiled cupola was designed by Brunelleschi and is described as a must-see by experts and travelers alike.",R.drawable.italy_cathedral,"Florence was a wealthy medieval city on account of its textile trade, and Florentines of this time thought of themselves as a city similar to that of ancient Rome. They therefore decided that in order to compete with other Tuscan cities, they would build the grandest church in the regions.");
        Places I4 = new Places("Italy","Grand Canal","Considered to be the main street of Venice, the roughly 2-mile Grand Canal is one of the city's most popular and highly photographed attractions. Recent travelers recommend hiring a gondolier for a romantic row along the canal. If you're hoping to do this option, plan to fork over between 80 and 120 euros (about $87 to $132) for the ride.",R.drawable.italy_canal,"The Grand Canal is famous worldwide for the centuries-old palaces which stand on both sides of the water. Most of them date from the 13th to the 18th century, a time in which existed the Venetian Republic. These magnificent buildings show the wealth Venetian families had at the time of the powerful Venetian Republic.");
        Places F1 = new Places("France","Notre-Dame Cathedral","Like the Eiffel Tower, the Notre-Dame Cathedral is seen as a Parisian icon. Located along the picturesque River Seine, the Notre-Dame Cathedral is considered a Gothic masterpiece and is often regarded as one of the best Gothic cathedrals of its kind in the world. Construction of the famous cathedral started in the late 12th century and final touches weren't made until nearly 200 years later. Once you get an eyeful of the cathedral yourself, you'll start to understand why it took so long.",R.drawable.france_notre,"The cathedral was initiated by Maurice de Sully, bishop of Paris, who about 1160 conceived the idea of converting into a single building, on a larger scale, the ruins of the two earlier basilicas. The foundation stone was laid by Pope Alexander III in 1163, and the high altar was consecrated in 1189.");
        Places F2 = new Places("France","Eiffel Tower","Today, the Eiffel Tower is still used for communication but is chiefly regarded for its grandeur. If you can believe it, many Parisians initially found this architectural marvel to be nothing more than an eyesore. Regardless, the Eiffel Tower today stands as one of the most visited tourist attractions in the world. Visitors can walk up to the first floor of the Eiffel Tower or take the elevator all the way up to the top, where they'll be treated with vast panoramic views of the city. While some recent visitors complain of long lines – especially during the summer – you can bypass the wait by booking your tickets online at the Eiffel Tower's website.",R.drawable.france_eiffel,"The Eiffel Tower was built to be one the main attractions at the Paris World's Fair in 1889. That year, the World's Fair covered the entire Champ de Mars in Paris and its focus was the vast constructions in iron and steel that were the great industrial advancement of that time.\n");
        Places F3 = new Places("France","Musée du Louvre","f you only had time to visit one museum in Paris, it should undoubtedly be the Musée du Louvre. That's because the Louvre is not only widely considered to be one of the best art museums in Europe, but one of the best in the world. The museum first opened its doors in 1793 and features more than 35,000 works of art on display. Here, you can get up close to a variety of art from different time periods and cultures. The Louvre features everything from Egyptian mummy tombs to ancient Grecian sculptures (including the renowned Winged Victory of Samothrace and curvaceous Venus de Milo). There are also thousands of paintings to peruse as well. Masterpieces such as \"Liberty Leading the People\" by Eugene Delacroix, \"The Raft of the Medusa\" by Théodore Géricault and Leonardo da Vinci's \"Mona Lisa,\" the museum's biggest star, can be found here.",R.drawable.france_louvre,"Originally built as a fortress in 1190, the Louvre was reconstructed in the 16th century to serve as a royal palace. During its time as a royal residence, the Louvre saw tremendous growth. Today, as a museum, the Louvre covers a total area of 652,300 square feet (60,600 square meters).");
        Places F4 = new Places("France","Musée d'Orsay","Housed in a former railway station along the Left Bank, the Musée d'Orsay is regarded for its rich collection of impressionist works. You'll see paintings by French artists like Degas, Monet, Cezanne and Van Gogh, among many, many others. The museum also houses a number of sculptures, as well as photography and even furniture displays. And if you climb to the museum's top balcony, you can catch a breathtaking view of the Sacré-Coeur Basilica through the museum's massive transparent clock.",R.drawable.france_orsay,"The museum building was originally a railway station, Gare d'Orsay, located next to the Seine river. Built on the site of the Palais d'Orsay, its central location was convenient for commuting travelers.[5] The station was constructed for the Chemin de Fer de Paris à Orléans and finished in time for the 1900 Exposition Universelle to the design of three architects: Lucien Magne, Émile Bénard and Victor Laloux. The Gare d'Orsay design was considered to be an \"anachronism.\"[6] Since trains were such a modern innovation for the time architects and designers alike expected a building that would embody the modern traits of this new mode of transportation. Gare d'Orsay instead gained inspiration from the past for the concept of the facade to the point of masking the cutting-edge technology within. It was the terminus for the railways of southwestern France until 1939.");
        Places F5 = new Places("France","Mont Saint-Michel Abbey","Surrounded by sea in the high tide and sand in low, Abbaye du Mont-Saint-Michel is one of France's most-toured sites outside of the popular Parisian landmarks. It's also a UNESCO World Heritage Site. Its first incarnation was raised on the 264-foot-high rock beginning in the 10th century, but additions were added well into the 19th century. Today, you can tour the abbey and the little village at its base, as well as several museums. Tours are offered year-round, but you can also traipse the massive structure on your own.",R.drawable.france_saint,"The island was originally called Mont-Tombe but became known as Mont-Saint-Michel in the 8th century, when St. Aubert, bishop of Avranches, built an oratory there after having a vision of the archangel St. Michael. It rapidly became a pilgrimage centre, and in 966 a Benedictine abbey was built there");
        Places T1 = new Places("Turkey","Blue Lagoon","This bay of turquoise water, with its finger of white sand curving around it, is so supernaturally vibrant that it has become a poster child for the Turquoise Coast. The sands of Belcekiz beach slip into the limpid shallows, creating Maldivian-esque swirling seascapes of blue and white, protected by the green-forested promontories which lie around it like sleeping dragons. Overhead, the skies are full of paragliders viewing the whole splendid shebang from the air.",R.drawable.turkey_lagoon,"The Blue Lagoon history dates back to 1976 and is formed next to the geothermal power plant. The lagoon was created by the excess water from the power plant, that is drilling for steam and hot water. The runoff is filtered straight into the Blue Lagoon, which is what heats the water.");
        Places T2 = new Places("Turkey","The pools of Pamukkale","The mineral springs that have cascaded down the hillside for thousands of years have created this extraordinary sight – Pamukkale means ‘cotton castle’ – in Turkey’s Büyük Menderes Valley. The series of natural pools of pale eau-de-nil water, cupped in shallow, organic-shaped basins of gleaming-white travertine, are terraced into the hillside, overspilling with the mineral-rich spring water that formed them and which appears to have frozen in time in petrified waterfalls, stalactites of limestone like wedding-cake icing dripping down the hillside. The spectacle gets busy with tourists, but often overlooked are the ancient ruins of the Greco-Roman spa town Hierapolis, built at the very top of the site, around the healing springs. Here you can bathe in Cleopatra’s very own hot bath, said to have been a gift from Mark Antony; once covered by the Roman temple of Apollo, the doric columns now lie in the water, and the pool is flanked with flowers.",R.drawable.turkey_pamukkale,"Pamukkale's terraces are made of travertine, a sedimentary rock deposited by mineral water from the hot springs.[1] In this area, there are 17 hot springs with temperatures ranging from 35 °C (95 °F) to 100 °C (212 °F). The water that emerges from the spring is transported 320 metres (1,050 ft) to the head of the travertine terraces and deposits calcium carbonate on a section 60 to 70 metres (200 to 230 ft) long covering an expanse of 24 metres (79 ft) to 30 metres (98 ft). When the water, supersaturated with calcium carbonate, reaches the surface, carbon dioxide de-gasses from it, and calcium carbonate is deposited. Calcium carbonate is deposited by the water as a soft gel which eventually crystallizes into travertine.");
        Places T3 = new Places("Turkey","The Fairy Chimneys of Cappadocia","High on the Anatolian plateau, the curious landscapes of Cappadocia resemble a fantasy world. Honey-coloured rocks have eroded into sculptural forms resembling minarets, magic mushrooms and what have become known as Fairy Chimneys, while underground, settlers since the Bronze Age have been busy carving out cave houses, churches and monasteries from the soft volcanic rock – even entire subterranean cities. The thing to do is take a hot-air balloon ride at sunrise or sunset; alternatively, see it on horseback or two wheels – or watch the spectacle from the terrace of your cave hotel in the town of Göreme (try Sultan Cave Suites for its rooftop, Museum Hotel or Kayakapi which all have outdoor pools; rustic-charming Cappadocia Cave Suites; or film-set-like Yunak Evleri) as hundreds of balloons drift overhead and the low sun casts apricot light on this extraordinary land. One of the most romantic spots on earth.",R.drawable.turkey_fairy,"The chimneys are a result of a geologic process that began millions of years ago, when volcanic eruptions rained ash across what would eventually become Turkey. That ash hardened into tuff, a porous rock, which was covered by a layer of basalt. Finally, the long work of erosion began.");
        Places T4 = new Places("Turkey","Ephesus","Turkey has a great number of ancient sites, most far less visited than similar sites in Italy and Greece; and Ephesus, now UNESCO-protected, is arguably the grandest of them all. The Temple of Artemis which stood in the ancient city of Ephesus was one of the original Seven Wonders of the World. Little remains of it now, but the remains of Ephesus are wondrous nonetheless. Set back from the Aegean coast, the settlement began 9,000 years ago. There Roman, Christian, Ottoman, Hellenistic and Greek monuments: colonnaded streets, temples, a huge amphitheatre, the Celsus library whose carved façade still stands today, archways framing the blue Mediterranean sky.",R.drawable.turkey_efes,"\u200BAlthough sacked by the Goths in 263 AD, Ephesus remained one of  the most important cities of the Byzantine Empire after the city of Constantinople in the 5th and 6th centuries. However, other destruction by the Arabs in the year 8th century AD caused a quick decline: the city was largely abandoned when the harbor was completely filled in with river silt despite repeated dredges during the city's history. The silt removed its access to the Aegean Sea. When the Seljuk Turks conquered it in the 11th century, it was a small village. The Byzantines resumed control in 1100 and kept control of the region until the end of the 13th century.  During the Byzantine period the major settlement was in its first place at Ayasoluk (Hagios  Theologos) Hill. The Emir of Aydin, a Turkish state, conquered the city in the 14th century. Starting from the 16th century, the city lost its importance and was ruled by the Ottoman Empire.");
        List<Places> pdata = new ArrayList<>();
        pdata.add(I1);
        pdata.add(I2);
        pdata.add(I3);
        pdata.add(I4);
        pdata.add(T1);
        pdata.add(T2);
        pdata.add(T3);
        pdata.add(T4);
        pdata.add(F1);
        pdata.add(F2);
        pdata.add(F3);
        pdata.add(F4);
        pdata.add(F5);
        return  pdata;


    }
    public static List<Places> getItaly(){
        Places I1 = new Places("Italy","Trevi Fountain","This site is best viewed at night when lights illuminate the fountain. However, some travelers lament the Trevi's many tourists and aggressive local street vendors (you'll likely have a hard time getting a crowd-free photo here). The Trevi Fountain sits off the Barberini metro stop and is about a 10-minute walk east of the Pantheon. It is free to visit 24/7. If you don't plan a visit on your own, you'll likely pass by the fountain if you sign up for one of the best Rome tours.",R.drawable.italy_trevi,"It was designed by Nicola Salvi and completed by Giuseppe Pannini in 1762. According to legend, those who toss coins into its waters will return to Rome. The fountain is located in Rome's Trevi district, abutting the Palazzo Poli.");
        Places I2 = new Places("Italy","Piazza della Signoria","Take your time wandering around, and if you get tired, grab a seat along the Loggia dei Lanzi, or make your way to a cafe near the Fountain of Neptune. Recent visitors said this is a must-see spot and a great area to people-watch, view magnificent sculptures and rest travel-weary feet (though past travelers recommended avoiding the restaurants in this area, calling them \"outrageously overpriced\"). To avoid the height of the crowds, visit in the early morning or the evening. Access to the area is free 24/7.",R.drawable.italy_piazza,"It is the main point of the origin and history of the Florentine Republic and still maintains its reputation as the political focus of the city. It is the meeting place of Florentines as well as the numerous tourists, located near Palazzo Vecchio and Piazza del Duomo and gateway to Uffizi Gallery.");
        Places I3 = new Places("Italy","Cathedral of Santa Maria del Fiore","The Cattedrale di Santa Maria del Fiore (known simply as the Duomo) is not only Florence's religious center, but it's also the city's most recognizable attraction. Occupying the Piazza del Duomo in the heart of the city, this massive Gothic cathedral was erected during the 14th century on the former site of the Roman church, Santa Reparata. You'll know you're in the right place when you find yourself straining your neck to see the church's massive, iconic dome and the intricate marble statues on its facade staring down at you. The red-tiled cupola was designed by Brunelleschi and is described as a must-see by experts and travelers alike.",R.drawable.italy_cathedral,"Florence was a wealthy medieval city on account of its textile trade, and Florentines of this time thought of themselves as a city similar to that of ancient Rome. They therefore decided that in order to compete with other Tuscan cities, they would build the grandest church in the regions.");
        Places I4 = new Places("Italy","Grand Canal","Considered to be the main street of Venice, the roughly 2-mile Grand Canal is one of the city's most popular and highly photographed attractions. Recent travelers recommend hiring a gondolier for a romantic row along the canal. If you're hoping to do this option, plan to fork over between 80 and 120 euros (about $87 to $132) for the ride.",R.drawable.italy_canal,"The Grand Canal is famous worldwide for the centuries-old palaces which stand on both sides of the water. Most of them date from the 13th to the 18th century, a time in which existed the Venetian Republic. These magnificent buildings show the wealth Venetian families had at the time of the powerful Venetian Republic.");
        List<Places> pdata = new ArrayList<>();
        pdata.add(I1);
        pdata.add(I2);
        pdata.add(I3);
        pdata.add(I4);
        return  pdata;


    }
    public static List<Places> getFrance(){
        Places F1 = new Places("France","Notre-Dame Cathedral","Like the Eiffel Tower, the Notre-Dame Cathedral is seen as a Parisian icon. Located along the picturesque River Seine, the Notre-Dame Cathedral is considered a Gothic masterpiece and is often regarded as one of the best Gothic cathedrals of its kind in the world. Construction of the famous cathedral started in the late 12th century and final touches weren't made until nearly 200 years later. Once you get an eyeful of the cathedral yourself, you'll start to understand why it took so long.",R.drawable.france_notre,"The cathedral was initiated by Maurice de Sully, bishop of Paris, who about 1160 conceived the idea of converting into a single building, on a larger scale, the ruins of the two earlier basilicas. The foundation stone was laid by Pope Alexander III in 1163, and the high altar was consecrated in 1189.");
        Places F2 = new Places("France","Eiffel Tower","Today, the Eiffel Tower is still used for communication but is chiefly regarded for its grandeur. If you can believe it, many Parisians initially found this architectural marvel to be nothing more than an eyesore. Regardless, the Eiffel Tower today stands as one of the most visited tourist attractions in the world. Visitors can walk up to the first floor of the Eiffel Tower or take the elevator all the way up to the top, where they'll be treated with vast panoramic views of the city. While some recent visitors complain of long lines – especially during the summer – you can bypass the wait by booking your tickets online at the Eiffel Tower's website.",R.drawable.france_eiffel,"The Eiffel Tower was built to be one the main attractions at the Paris World's Fair in 1889. That year, the World's Fair covered the entire Champ de Mars in Paris and its focus was the vast constructions in iron and steel that were the great industrial advancement of that time.\n");
        Places F3 = new Places("France","Musée du Louvre","f you only had time to visit one museum in Paris, it should undoubtedly be the Musée du Louvre. That's because the Louvre is not only widely considered to be one of the best art museums in Europe, but one of the best in the world. The museum first opened its doors in 1793 and features more than 35,000 works of art on display. Here, you can get up close to a variety of art from different time periods and cultures. The Louvre features everything from Egyptian mummy tombs to ancient Grecian sculptures (including the renowned Winged Victory of Samothrace and curvaceous Venus de Milo). There are also thousands of paintings to peruse as well. Masterpieces such as \"Liberty Leading the People\" by Eugene Delacroix, \"The Raft of the Medusa\" by Théodore Géricault and Leonardo da Vinci's \"Mona Lisa,\" the museum's biggest star, can be found here.",R.drawable.france_louvre,"Originally built as a fortress in 1190, the Louvre was reconstructed in the 16th century to serve as a royal palace. During its time as a royal residence, the Louvre saw tremendous growth. Today, as a museum, the Louvre covers a total area of 652,300 square feet (60,600 square meters).");
        Places F4 = new Places("France","Musée d'Orsay","Housed in a former railway station along the Left Bank, the Musée d'Orsay is regarded for its rich collection of impressionist works. You'll see paintings by French artists like Degas, Monet, Cezanne and Van Gogh, among many, many others. The museum also houses a number of sculptures, as well as photography and even furniture displays. And if you climb to the museum's top balcony, you can catch a breathtaking view of the Sacré-Coeur Basilica through the museum's massive transparent clock.",R.drawable.france_orsay,"The museum building was originally a railway station, Gare d'Orsay, located next to the Seine river. Built on the site of the Palais d'Orsay, its central location was convenient for commuting travelers.[5] The station was constructed for the Chemin de Fer de Paris à Orléans and finished in time for the 1900 Exposition Universelle to the design of three architects: Lucien Magne, Émile Bénard and Victor Laloux. The Gare d'Orsay design was considered to be an \"anachronism.\"[6] Since trains were such a modern innovation for the time architects and designers alike expected a building that would embody the modern traits of this new mode of transportation. Gare d'Orsay instead gained inspiration from the past for the concept of the facade to the point of masking the cutting-edge technology within. It was the terminus for the railways of southwestern France until 1939.");
        Places F5 = new Places("France","Mont Saint-Michel Abbey","Surrounded by sea in the high tide and sand in low, Abbaye du Mont-Saint-Michel is one of France's most-toured sites outside of the popular Parisian landmarks. It's also a UNESCO World Heritage Site. Its first incarnation was raised on the 264-foot-high rock beginning in the 10th century, but additions were added well into the 19th century. Today, you can tour the abbey and the little village at its base, as well as several museums. Tours are offered year-round, but you can also traipse the massive structure on your own.",R.drawable.france_saint,"The island was originally called Mont-Tombe but became known as Mont-Saint-Michel in the 8th century, when St. Aubert, bishop of Avranches, built an oratory there after having a vision of the archangel St. Michael. It rapidly became a pilgrimage centre, and in 966 a Benedictine abbey was built there");
        List<Places> pdata = new ArrayList<>();
        pdata.add(F1);
        pdata.add(F2);
        pdata.add(F3);
        pdata.add(F4);
        pdata.add(F5);
        return  pdata;


    }
    public static List<Places> getTurkey(){
        Places T1 = new Places("Turkey","Blue Lagoon","This bay of turquoise water, with its finger of white sand curving around it, is so supernaturally vibrant that it has become a poster child for the Turquoise Coast. The sands of Belcekiz beach slip into the limpid shallows, creating Maldivian-esque swirling seascapes of blue and white, protected by the green-forested promontories which lie around it like sleeping dragons. Overhead, the skies are full of paragliders viewing the whole splendid shebang from the air.",R.drawable.turkey_lagoon,"The Blue Lagoon history dates back to 1976 and is formed next to the geothermal power plant. The lagoon was created by the excess water from the power plant, that is drilling for steam and hot water. The runoff is filtered straight into the Blue Lagoon, which is what heats the water.");
        Places T2 = new Places("Turkey","The pools of Pamukkale","The mineral springs that have cascaded down the hillside for thousands of years have created this extraordinary sight – Pamukkale means ‘cotton castle’ – in Turkey’s Büyük Menderes Valley. The series of natural pools of pale eau-de-nil water, cupped in shallow, organic-shaped basins of gleaming-white travertine, are terraced into the hillside, overspilling with the mineral-rich spring water that formed them and which appears to have frozen in time in petrified waterfalls, stalactites of limestone like wedding-cake icing dripping down the hillside. The spectacle gets busy with tourists, but often overlooked are the ancient ruins of the Greco-Roman spa town Hierapolis, built at the very top of the site, around the healing springs. Here you can bathe in Cleopatra’s very own hot bath, said to have been a gift from Mark Antony; once covered by the Roman temple of Apollo, the doric columns now lie in the water, and the pool is flanked with flowers.",R.drawable.turkey_pamukkale,"Pamukkale's terraces are made of travertine, a sedimentary rock deposited by mineral water from the hot springs.[1] In this area, there are 17 hot springs with temperatures ranging from 35 °C (95 °F) to 100 °C (212 °F). The water that emerges from the spring is transported 320 metres (1,050 ft) to the head of the travertine terraces and deposits calcium carbonate on a section 60 to 70 metres (200 to 230 ft) long covering an expanse of 24 metres (79 ft) to 30 metres (98 ft). When the water, supersaturated with calcium carbonate, reaches the surface, carbon dioxide de-gasses from it, and calcium carbonate is deposited. Calcium carbonate is deposited by the water as a soft gel which eventually crystallizes into travertine.");
        Places T3 = new Places("Turkey","The Fairy Chimneys of Cappadocia","High on the Anatolian plateau, the curious landscapes of Cappadocia resemble a fantasy world. Honey-coloured rocks have eroded into sculptural forms resembling minarets, magic mushrooms and what have become known as Fairy Chimneys, while underground, settlers since the Bronze Age have been busy carving out cave houses, churches and monasteries from the soft volcanic rock – even entire subterranean cities. The thing to do is take a hot-air balloon ride at sunrise or sunset; alternatively, see it on horseback or two wheels – or watch the spectacle from the terrace of your cave hotel in the town of Göreme (try Sultan Cave Suites for its rooftop, Museum Hotel or Kayakapi which all have outdoor pools; rustic-charming Cappadocia Cave Suites; or film-set-like Yunak Evleri) as hundreds of balloons drift overhead and the low sun casts apricot light on this extraordinary land. One of the most romantic spots on earth.",R.drawable.turkey_fairy,"The chimneys are a result of a geologic process that began millions of years ago, when volcanic eruptions rained ash across what would eventually become Turkey. That ash hardened into tuff, a porous rock, which was covered by a layer of basalt. Finally, the long work of erosion began.");
        Places T4 = new Places("Turkey","Ephesus","Turkey has a great number of ancient sites, most far less visited than similar sites in Italy and Greece; and Ephesus, now UNESCO-protected, is arguably the grandest of them all. The Temple of Artemis which stood in the ancient city of Ephesus was one of the original Seven Wonders of the World. Little remains of it now, but the remains of Ephesus are wondrous nonetheless. Set back from the Aegean coast, the settlement began 9,000 years ago. There Roman, Christian, Ottoman, Hellenistic and Greek monuments: colonnaded streets, temples, a huge amphitheatre, the Celsus library whose carved façade still stands today, archways framing the blue Mediterranean sky.",R.drawable.turkey_efes,"\u200BAlthough sacked by the Goths in 263 AD, Ephesus remained one of  the most important cities of the Byzantine Empire after the city of Constantinople in the 5th and 6th centuries. However, other destruction by the Arabs in the year 8th century AD caused a quick decline: the city was largely abandoned when the harbor was completely filled in with river silt despite repeated dredges during the city's history. The silt removed its access to the Aegean Sea. When the Seljuk Turks conquered it in the 11th century, it was a small village. The Byzantines resumed control in 1100 and kept control of the region until the end of the 13th century.  During the Byzantine period the major settlement was in its first place at Ayasoluk (Hagios  Theologos) Hill. The Emir of Aydin, a Turkish state, conquered the city in the 14th century. Starting from the 16th century, the city lost its importance and was ruled by the Ottoman Empire.");
        List<Places> pdata = new ArrayList<>();

        pdata.add(T1);
        pdata.add(T2);
        pdata.add(T3);
        pdata.add(T4);

        return  pdata;


    }

}
